  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "https://www.databotics.ai/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Conferences and Courses"
  weight = 500
  identifier = "accomplishments"

  [[main]]
  name = "Conferences"
  weight = 510
  identifier = "awards"
  url = "https://github.com/carlosjimenez88M/talks"
  parent = "accomplishments"  

  [[main]]
  name = "Courses"
  weight = 520
  identifier = "certifications"
  url = "https://github.com/carlosjimenez88M/Courses"
  parent = "accomplishments"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"